name: mobileapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you plan to publish the app

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  mapbox_maps_flutter: ^2.9.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  flutter_secure_storage: ^9.2.4
  http: ^1.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/