name: mobileapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you plan to publish the app

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
    
    

  # UI and icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7

  # Mapbox & location
  mapbox_maps_flutter: ^2.9.0
  geolocator: ^10.1.0
  permission_handler: ^11.3.0

  # Storage and networking
  flutter_secure_storage: ^8.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
