name: mobileapp
description: A new Flutter project.

publish_to: "none" # Remove this line if you plan to publish the app

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  flutter_secure_storage: ^9.2.4
  http: ^1.2.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  mime: ^1.0.4
  dio: ^5.4.0
  flutter_dotenv: ^6.0.0
  google_fonts: ^6.1.0
  fpdart: ^1.1.1
  riverpod_annotation: ^2.3.5
  flutter_riverpod: ^2.5.1
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.5
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/background/
    - .env
